[package]
name = "kaspa-miner"
version = "0.1.0"
edition = "2021"
license = "MIT/Apache-2.0"
authors = ["Elichai <elichai.turkel@gmail.com>"]
readme = "README.md"
description = "A fast CPU miner for Kaspa"
categories = ["command-line-utilities"]
keywords = ["blockchain", "cli"]

[dependencies]
tonic = "0.6"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
prost = "0.9"
futures-util = "0.3"
tokio-stream = "0.1"
sha3 = { git = "https://github.com/elichai/hashes", branch = "cSHAKE" }
once_cell = "1"
num_cpus = "1"
rand = "0.8"
blake2b_simd = "0.5"
structopt = { version = "0.3", features = ["color" ]}
log = "0.4"
env_logger = "0.9"

[build-dependencies]
tonic-build = { version = "0.6", default-features = false, features = ["prost", "transport"] }

[profile.release]
opt-level = 3
debug = false
split-debuginfo = '...' # Platform-specific.
debug-assertions = false
overflow-checks = false
lto = true
panic = 'unwind'
incremental = false
codegen-units = 1
rpath = false
rustflags = ["-C target-cpu=native", "-C tune-cpu=native"]

[target.x86_64-unknown-linux-gnu]
linker = "rust-lld"